// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/check-website.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/env.ts
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url.replace(/\/+$/, "");
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
async function callPublicFunction(name, init = {}) {
  const key = supabasePublishableKey();
  const url = new URL(`${supabaseProjectUrl()}/functions/v1/${name}`);
  for (const [k, v] of Object.entries(init.query ?? {})) url.searchParams.set(k, v);
  const res = await fetch(url.toString(), {
    method: init.method ?? "GET",
    headers: {
      "Content-Type": "application/json",
      apikey: key,
      Authorization: `Bearer ${key}`
    },
    body: init.body === void 0 ? void 0 : JSON.stringify(init.body)
  });
  const text = await res.text();
  let parsed = text;
  try {
    parsed = JSON.parse(text);
  } catch {
  }
  if (!res.ok) {
    const message = (parsed && typeof parsed === "object" && "message" in parsed ? String(parsed.message) : void 0) ?? `Request failed with status ${res.status}`;
    throw new Error(message);
  }
  return parsed;
}

// src/lib/mcp/tools/check-website.ts
function normalizeUrl(input) {
  const trimmed = input.trim();
  const withScheme = /^https?:\/\//i.test(trimmed) ? trimmed : `https://${trimmed}`;
  let parsed;
  try {
    parsed = new URL(withScheme);
  } catch {
    throw new ToolError(`"${input}" is not a valid website URL or domain.`);
  }
  if (!parsed.hostname.includes(".")) {
    throw new ToolError(`"${input}" is not a valid website URL or domain.`);
  }
  return parsed.toString();
}
var check_website_default = defineTool({
  name: "check_website",
  title: "Check website trustworthiness",
  description: "Run a full legitimacy check on a website URL or domain and return its trust score (0-100), verdict (safe / caution / danger), summary, red flags and positive signals. Analysis can take up to a minute for domains that have not been checked recently.",
  inputSchema: {
    url: z.string().describe("Website URL or bare domain to analyze, e.g. example.com")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ url }) => {
    const target = normalizeUrl(url);
    const result = await callPublicFunction("analyze-url", {
      method: "POST",
      body: { url: target }
    });
    if (result?.success === false) {
      throw new ToolError(String(result.message ?? "Could not analyze this website."));
    }
    const analysis = result?.data ?? result;
    const summary = {
      url: target,
      trustScore: analysis?.trustScore ?? null,
      verdict: analysis?.verdict ?? null,
      summary: analysis?.summary ?? null,
      confidence: analysis?.confidence?.level ?? null,
      redFlags: analysis?.details?.redFlags ?? [],
      positiveSignals: analysis?.details?.positiveSignals ?? [],
      domain: analysis?.details?.domain ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-threat-feed.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_threat_feed_default = defineTool2({
  name: "list_threat_feed",
  title: "List recent scam threats",
  description: "List recent scam and fraud threats from TrustWorthyCheck's public threat feed (aggregated from public security and consumer-protection sources).",
  inputSchema: {
    limit: z2.number().int().describe("Maximum number of threats to return (1-50). Defaults to 20.").optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const capped = Math.min(Math.max(limit ?? 20, 1), 50);
    const data = await callPublicFunction("public-threats", {
      query: { limit: String(capped) }
    });
    const threats = Array.isArray(data) ? data : data?.threats ?? data?.data ?? [];
    if (!Array.isArray(threats)) {
      throw new ToolError2("Unexpected response from the threat feed.");
    }
    const items = threats.slice(0, capped);
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { threats: items }
    };
  }
});

// src/lib/mcp/tools/list-community-reports.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_community_reports_default = defineTool3({
  name: "list_community_reports",
  title: "List community site reports",
  description: "List public community-submitted reports about suspicious or scam websites on TrustWorthyCheck.",
  inputSchema: {
    limit: z3.number().int().describe("Maximum number of reports to return (1-50). Defaults to 20.").optional(),
    sort: z3.enum(["recent", "most_reported"]).describe("Sort order. Defaults to recent.").optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ limit, sort }) => {
    const capped = Math.min(Math.max(limit ?? 20, 1), 50);
    const data = await callPublicFunction("public-reports", {
      query: { limit: String(capped), sort: sort ?? "recent" }
    });
    const reports = Array.isArray(data) ? data : data?.reports ?? data?.data ?? [];
    if (!Array.isArray(reports)) {
      throw new ToolError3("Unexpected response from the community reports service.");
    }
    const items = reports.slice(0, capped);
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { reports: items }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "trustworthy",
  title: "TrustWorthy",
  version: "0.1.0",
  instructions: "Tools from TrustWorthyCheck, a website legitimacy and scam checker. Use `check_website` to score a URL or domain for trustworthiness (domain age, TLS, reputation, business transparency, scam reports). Use `list_threat_feed` for recent scam threats and `list_community_reports` for community-submitted suspicious sites. All data is public; no user account is required.",
  tools: [check_website_default, list_threat_feed_default, list_community_reports_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
